p8105_hw2_jkh2157
================
2025-09-30

## Loading Libraries

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(knitr)
library(readxl)
```

## Problem 1

Step 1a: Clean the data in pols-month

``` r
pols_df=
  read_csv("datasets/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate (mon, into = c("year","month","day"),sep="-") %>% 
  mutate(
    month = recode(month,`01`="Jan",`02`="Feb",`03`="Mar",`04`="Apr",`05`="May",`06`="Jun",`07`="Jul",`08`="Aug",`09`="Sep",`10`="Oct",`11`="Nov",`12`="Dec"),
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem ==1 ~ "dem"
    ),
    year=as.character(year)
  ) %>% 
  select(year,month,president,everything(),-day,-prez_gop,-prez_dem)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
knitr::kable(head(pols_df,10))
```

| year | month | president | gov_gop | sen_gop | rep_gop | gov_dem | sen_dem | rep_dem |
|:-----|:------|:----------|--------:|--------:|--------:|--------:|--------:|--------:|
| 1947 | Jan   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |
| 1947 | Feb   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |
| 1947 | Mar   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |
| 1947 | Apr   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |
| 1947 | May   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |
| 1947 | Jun   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |
| 1947 | Jul   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |
| 1947 | Aug   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |
| 1947 | Sep   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |
| 1947 | Oct   | dem       |      23 |      51 |     253 |      23 |      45 |     198 |

Step 1b: Clean the data for snp.csv

``` r
snp_df=
  read_csv("datasets/fivethirtyeight_datasets/snp.csv") %>% 
  separate(date, into=c("month","date","year"), sep = "/") %>% 
  mutate(
    month = recode(month,`1`="Jan",`2`="Feb",`3`="Mar",`4`="Apr",`5`="May",`6`="Jun",`7`="Jul",`8`="Aug",`9`="Sep",`10`="Oct",`11`="Nov",`12`="Dec"),
    year=case_when(
      as.numeric(year)>=50 ~ paste0("19",year),
      as.numeric(year)<50 ~ paste0("20",year)
    )) %>% 
  mutate(year=as.character(year)) %>% 
  select(year,month,close) %>% 
  arrange(year,month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
knitr::kable(head(snp_df,10))
```

| year | month | close |
|:-----|:------|------:|
| 1950 | Apr   | 17.96 |
| 1950 | Aug   | 18.42 |
| 1950 | Dec   | 20.43 |
| 1950 | Feb   | 17.22 |
| 1950 | Jan   | 17.05 |
| 1950 | Jul   | 17.84 |
| 1950 | Jun   | 17.69 |
| 1950 | Mar   | 17.29 |
| 1950 | May   | 18.78 |
| 1950 | Nov   | 19.51 |

Step 1c: tidy unemploymeny data

``` r
unemployment_df=
  read_csv("datasets/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols=jan:dec,
    names_to="month",
    values_to="unemployment") %>% 
  mutate(
    month=str_to_title(month),
    year=as.character(year)) %>% 
  select(year,month,unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
knitr::kable(head(unemployment_df,10))
```

| year | month | unemployment |
|:-----|:------|-------------:|
| 1948 | Jan   |          3.4 |
| 1948 | Feb   |          3.8 |
| 1948 | Mar   |          4.0 |
| 1948 | Apr   |          3.9 |
| 1948 | May   |          3.5 |
| 1948 | Jun   |          3.6 |
| 1948 | Jul   |          3.6 |
| 1948 | Aug   |          3.9 |
| 1948 | Sep   |          3.8 |
| 1948 | Oct   |          3.7 |

Step 1d: merge data sets

``` r
final_df=left_join(pols_df,snp_df,by=c("year","month"))
final_df=left_join(final_df,unemployment_df,by=c("year","month"))
knitr::kable(head(final_df,15))
```

| year | month | president | gov_gop | sen_gop | rep_gop | gov_dem | sen_dem | rep_dem | close | unemployment |
|:---|:---|:---|---:|---:|---:|---:|---:|---:|---:|---:|
| 1947 | Jan | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Feb | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Mar | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Apr | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | May | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Jun | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Jul | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Aug | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Sep | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Oct | dem | 23 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Nov | dem | 24 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1947 | Dec | dem | 24 | 51 | 253 | 23 | 45 | 198 | NA | NA |
| 1948 | Jan | dem | 22 | 53 | 253 | 24 | 48 | 198 | NA | 3.4 |
| 1948 | Feb | dem | 22 | 53 | 253 | 24 | 48 | 198 | NA | 3.8 |
| 1948 | Mar | dem | 22 | 53 | 253 | 24 | 48 | 198 | NA | 4.0 |

The pols data set (822 rows and 9 columns) contains the monthly counts
of Democratic and Republican governors,senators, and representatives.
The snp data set (787 rows and 3 columns) looks at the monthly closing
values of the S&P index, starting in 1950 which explains why there are
some NA values. The unemployment data set (816 rows and 3 columns)
reports monthly US unemployment rates starting in 1948. After cleaning
and merging these data sets we get a new frame that ranges from Jan 1947
to Jun 2015, with variables including year, month, president,
congressional bodies, stock market performance (close), and unemployment
rates. The dimensions of the final table contains 822 rows and 11
columns.

## Problem 2

Step 2a: Cleaning up mrTrash

``` r
mr_trash_df=
  read_excel("datasets/trash_wheel_data2.xlsx", sheet="Mr. Trash Wheel", range = "A2:N710") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
mutate(
  sports_balls=as.integer(round(sports_balls)),
  identity = "mr",
  year=as.numeric(year)
)
knitr::kable(head(mr_trash_df,10))
```

| dumpster | month | year | date | weight_tons | volume_cubic_yards | plastic_bottles | polystyrene | cigarette_butts | glass_bottles | plastic_bags | wrappers | sports_balls | homes_powered | identity |
|---:|:---|---:|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| 1 | May | 2014 | 2014-05-16 | 4.31 | 18 | 1450 | 1820 | 126000 | 72 | 584 | 1162 | 7 | 0 | mr |
| 2 | May | 2014 | 2014-05-16 | 2.74 | 13 | 1120 | 1030 | 91000 | 42 | 496 | 874 | 5 | 0 | mr |
| 3 | May | 2014 | 2014-05-16 | 3.45 | 15 | 2450 | 3100 | 105000 | 50 | 1080 | 2032 | 6 | 0 | mr |
| 4 | May | 2014 | 2014-05-17 | 3.10 | 15 | 2380 | 2730 | 100000 | 52 | 896 | 1971 | 6 | 0 | mr |
| 5 | May | 2014 | 2014-05-17 | 4.06 | 18 | 980 | 870 | 120000 | 72 | 368 | 753 | 7 | 0 | mr |
| 6 | May | 2014 | 2014-05-20 | 2.71 | 13 | 1430 | 2140 | 90000 | 46 | 672 | 1144 | 5 | 0 | mr |
| 7 | May | 2014 | 2014-05-21 | 1.91 | 8 | 910 | 1090 | 56000 | 32 | 416 | 692 | 3 | 0 | mr |
| 8 | May | 2014 | 2014-05-28 | 3.70 | 16 | 3580 | 4310 | 112000 | 58 | 1552 | 3015 | 6 | 0 | mr |
| 9 | June | 2014 | 2014-06-05 | 2.52 | 14 | 2400 | 2790 | 98000 | 49 | 984 | 1988 | 6 | 0 | mr |
| 10 | June | 2014 | 2014-06-11 | 3.76 | 18 | 1340 | 1730 | 130000 | 75 | 448 | 1066 | 7 | 0 | mr |

Step 2b: Cleaning up Professor Trash

``` r
prof_trash_df=
  read_excel("datasets/trash_wheel_data2.xlsx", sheet="Professor Trash Wheel", range="A2:M135") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(
    identity="prof",
    year=as.numeric(year)
  )
knitr::kable(head(prof_trash_df,10))
```

| dumpster | month | year | date | weight_tons | volume_cubic_yards | plastic_bottles | polystyrene | cigarette_butts | glass_bottles | plastic_bags | wrappers | homes_powered | identity |
|---:|:---|---:|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| 1 | January | 2017 | 2017-01-02 | 1.79 | 15 | 1950 | 6080 | 19700 | 8 | 3100 | 15600 | 29.83333 | prof |
| 2 | January | 2017 | 2017-01-30 | 1.58 | 15 | 9540 | 11230 | 17600 | 14 | 5630 | 16700 | 26.33333 | prof |
| 3 | February | 2017 | 2017-02-26 | 2.32 | 18 | 8350 | 9210 | 12000 | 19 | 6430 | 12400 | 38.66667 | prof |
| 4 | February | 2017 | 2017-02-26 | 3.72 | 15 | 8590 | 1030 | 13000 | 21 | 5870 | 11030 | 62.00000 | prof |
| 5 | February | 2017 | 2017-02-28 | 1.45 | 15 | 7830 | 9950 | 16000 | 18 | 7450 | 15340 | 24.16667 | prof |
| 6 | March | 2017 | 2017-03-30 | 1.71 | 15 | 8210 | 10340 | 14000 | 23 | 9560 | 13470 | 28.50000 | prof |
| 7 | April | 2017 | 2017-04-01 | 1.82 | 15 | 9830 | 11020 | 17000 | 26 | 11500 | 18620 | 30.33333 | prof |
| 8 | April | 2017 | 2017-04-20 | 2.37 | 15 | 9240 | 8760 | 15000 | 14 | 9970 | 14670 | 39.50000 | prof |
| 9 | May | 2017 | 2017-05-10 | 2.64 | 15 | 9540 | 8810 | 17000 | 28 | 12340 | 16580 | 44.00000 | prof |
| 10 | May | 2017 | 2017-05-26 | 2.78 | 15 | 8230 | 7800 | 13000 | 22 | 13450 | 17220 | 46.33333 | prof |

Step 2c: Cleaning up Gwynnda data

``` r
gwyn_trash_df=
  read_excel("datasets/trash_wheel_data2.xlsx", sheet="Gwynns Falls Trash Wheel", range = "A2:L352") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(
    identity="gwynn",
    year=as.numeric(year)
  )
knitr::kable(head(gwyn_trash_df,10))
```

| dumpster | month | year | date | weight_tons | volume_cubic_yards | plastic_bottles | polystyrene | cigarette_butts | plastic_bags | wrappers | homes_powered | identity |
|---:|:---|---:|:---|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| 1 | July | 2021 | 2021-07-03 | 0.93 | 15 | 1200 | 360 | 3400 | 1800 | NA | 15.50000 | gwynn |
| 2 | July | 2021 | 2021-07-07 | 2.26 | 15 | 2000 | 240 | 3900 | 2200 | NA | 37.66667 | gwynn |
| 3 | July | 2021 | 2021-07-07 | 1.62 | 15 | 1800 | 270 | 2900 | 2400 | NA | 27.00000 | gwynn |
| 4 | July | 2021 | 2021-07-16 | 1.76 | 15 | 1000 | 180 | 2100 | 1800 | NA | 29.33333 | gwynn |
| 5 | July | 2021 | 2021-07-30 | 1.53 | 15 | 2100 | 240 | 4000 | 2700 | NA | 25.50000 | gwynn |
| 6 | August | 2021 | 2021-08-11 | 2.06 | 15 | 2400 | 360 | 3900 | 3000 | NA | 34.33333 | gwynn |
| 7 | August | 2021 | 2021-08-14 | 1.90 | 15 | 2700 | 320 | 4200 | 3200 | NA | 31.66667 | gwynn |
| 8 | August | 2021 | 2021-08-16 | 2.16 | 15 | 3000 | 320 | 4000 | 3600 | NA | 36.00000 | gwynn |
| 9 | August | 2021 | 2021-08-16 | 2.60 | 15 | 980 | 180 | 1800 | 1000 | NA | 43.33333 | gwynn |
| 10 | August | 2021 | 2021-08-17 | 3.21 | 15 | 240 | 42 | 400 | 360 | NA | 53.50000 | gwynn |

Step 2d: merging the data sets

``` r
trash_wheels = bind_rows(mr_trash_df,prof_trash_df,gwyn_trash_df)

knitr::kable(head(trash_wheels,15))
```

| dumpster | month | year | date | weight_tons | volume_cubic_yards | plastic_bottles | polystyrene | cigarette_butts | glass_bottles | plastic_bags | wrappers | sports_balls | homes_powered | identity |
|---:|:---|---:|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| 1 | May | 2014 | 2014-05-16 | 4.31 | 18 | 1450 | 1820 | 126000 | 72 | 584 | 1162 | 7 | 0 | mr |
| 2 | May | 2014 | 2014-05-16 | 2.74 | 13 | 1120 | 1030 | 91000 | 42 | 496 | 874 | 5 | 0 | mr |
| 3 | May | 2014 | 2014-05-16 | 3.45 | 15 | 2450 | 3100 | 105000 | 50 | 1080 | 2032 | 6 | 0 | mr |
| 4 | May | 2014 | 2014-05-17 | 3.10 | 15 | 2380 | 2730 | 100000 | 52 | 896 | 1971 | 6 | 0 | mr |
| 5 | May | 2014 | 2014-05-17 | 4.06 | 18 | 980 | 870 | 120000 | 72 | 368 | 753 | 7 | 0 | mr |
| 6 | May | 2014 | 2014-05-20 | 2.71 | 13 | 1430 | 2140 | 90000 | 46 | 672 | 1144 | 5 | 0 | mr |
| 7 | May | 2014 | 2014-05-21 | 1.91 | 8 | 910 | 1090 | 56000 | 32 | 416 | 692 | 3 | 0 | mr |
| 8 | May | 2014 | 2014-05-28 | 3.70 | 16 | 3580 | 4310 | 112000 | 58 | 1552 | 3015 | 6 | 0 | mr |
| 9 | June | 2014 | 2014-06-05 | 2.52 | 14 | 2400 | 2790 | 98000 | 49 | 984 | 1988 | 6 | 0 | mr |
| 10 | June | 2014 | 2014-06-11 | 3.76 | 18 | 1340 | 1730 | 130000 | 75 | 448 | 1066 | 7 | 0 | mr |
| 11 | June | 2014 | 2014-06-11 | 3.43 | 15 | 740 | 869 | 110000 | 38 | 344 | 544 | 6 | 0 | mr |
| 12 | June | 2014 | 2014-06-12 | 4.17 | 19 | 950 | 1140 | 133000 | 45 | 520 | 727 | 8 | 0 | mr |
| 13 | June | 2014 | 2014-06-13 | 5.13 | 15 | 530 | 630 | 104000 | 58 | 224 | 361 | 6 | 0 | mr |
| 14 | June | 2014 | 2014-06-13 | 4.17 | 15 | 840 | 760 | 100000 | 62 | 344 | 631 | 6 | 0 | mr |
| 15 | June | 2014 | 2014-06-19 | 3.28 | 15 | 1130 | 1350 | 102000 | 64 | 432 | 883 | 6 | 0 | mr |

``` r
total_weight_prof = prof_trash_df %>%
  summarise(total_weight = sum(weight_tons, na.rm = TRUE))

total_cigs_gwyn = gwyn_trash_df %>%
  filter(year == 2022, month == "June") %>%
  summarise(total_cigs = sum(cigarette_butts, na.rm = TRUE))
```

The combined Trash Wheel dataset contains **1188** observations and
**15** variables. Some key variables included the weight of trash
collected, cigarette butts collected, plastic bottles, and identifier
for which trash wheel the data came from. Professor Trash Wheel
collected a total of **282.26** tons of trash. In June 2022, Gwyn
collected **1.812^{4}** cigarette butts.

## Problem 3

Step 3a:import and clean the data

``` r
zori_raw=
  read_csv("datasets/zillow_data/ZORI.csv",na=c("NA",".",""), show_col_types=FALSE) %>% 
  janitor::clean_names()

zip_raw=
  read_csv("datasets/zillow_data/ZIP.csv",na=c("NA",".",""),show_col_types = FALSE) %>% 
  janitor::clean_names()

zori_clean =
  zori_raw |>
  mutate(zip = as.character(region_name)) |>
  relocate(zip)

zip_clean =
  zip_raw |>
  mutate(zip = as.character(zip_code)) |>
  select(zip,
         borough = county,
         neighborhood)

knitr::kable(head(zip_clean,10))
```

| zip   | borough | neighborhood               |
|:------|:--------|:---------------------------|
| 10451 | Bronx   | High Bridge and Morrisania |
| 10452 | Bronx   | High Bridge and Morrisania |
| 10453 | Bronx   | Central Bronx              |
| 10454 | Bronx   | Hunts Point and Mott Haven |
| 10455 | Bronx   | Hunts Point and Mott Haven |
| 10456 | Bronx   | High Bridge and Morrisania |
| 10457 | Bronx   | Central Bronx              |
| 10458 | Bronx   | Bronx Park and Fordham     |
| 10459 | Bronx   | Hunts Point and Mott Haven |
| 10460 | Bronx   | Central Bronx              |

``` r
knitr::kable(head(zori_clean,10))
```

| zip | region_id | size_rank | region_name | region_type | state_name | state | city | metro | county_name | x2015_01_31 | x2015_02_28 | x2015_03_31 | x2015_04_30 | x2015_05_31 | x2015_06_30 | x2015_07_31 | x2015_08_31 | x2015_09_30 | x2015_10_31 | x2015_11_30 | x2015_12_31 | x2016_01_31 | x2016_02_29 | x2016_03_31 | x2016_04_30 | x2016_05_31 | x2016_06_30 | x2016_07_31 | x2016_08_31 | x2016_09_30 | x2016_10_31 | x2016_11_30 | x2016_12_31 | x2017_01_31 | x2017_02_28 | x2017_03_31 | x2017_04_30 | x2017_05_31 | x2017_06_30 | x2017_07_31 | x2017_08_31 | x2017_09_30 | x2017_10_31 | x2017_11_30 | x2017_12_31 | x2018_01_31 | x2018_02_28 | x2018_03_31 | x2018_04_30 | x2018_05_31 | x2018_06_30 | x2018_07_31 | x2018_08_31 | x2018_09_30 | x2018_10_31 | x2018_11_30 | x2018_12_31 | x2019_01_31 | x2019_02_28 | x2019_03_31 | x2019_04_30 | x2019_05_31 | x2019_06_30 | x2019_07_31 | x2019_08_31 | x2019_09_30 | x2019_10_31 | x2019_11_30 | x2019_12_31 | x2020_01_31 | x2020_02_29 | x2020_03_31 | x2020_04_30 | x2020_05_31 | x2020_06_30 | x2020_07_31 | x2020_08_31 | x2020_09_30 | x2020_10_31 | x2020_11_30 | x2020_12_31 | x2021_01_31 | x2021_02_28 | x2021_03_31 | x2021_04_30 | x2021_05_31 | x2021_06_30 | x2021_07_31 | x2021_08_31 | x2021_09_30 | x2021_10_31 | x2021_11_30 | x2021_12_31 | x2022_01_31 | x2022_02_28 | x2022_03_31 | x2022_04_30 | x2022_05_31 | x2022_06_30 | x2022_07_31 | x2022_08_31 | x2022_09_30 | x2022_10_31 | x2022_11_30 | x2022_12_31 | x2023_01_31 | x2023_02_28 | x2023_03_31 | x2023_04_30 | x2023_05_31 | x2023_06_30 | x2023_07_31 | x2023_08_31 | x2023_09_30 | x2023_10_31 | x2023_11_30 | x2023_12_31 | x2024_01_31 | x2024_02_29 | x2024_03_31 | x2024_04_30 | x2024_05_31 | x2024_06_30 | x2024_07_31 | x2024_08_31 |
|:---|---:|---:|---:|:---|:---|:---|:---|:---|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| 11368 | 62080 | 4 | 11368 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | Queens County | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 2322.418 | 2282.500 |
| 11385 | 62093 | 7 | 11385 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | Queens County | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 2266.140 | 2292.023 | 2320.788 | 2343.339 | 2337.120 | 2345.339 | 2320.083 | 2326.450 | 2310.855 | 2313.101 | 2316.134 | 2309.757 | 2336.220 | 2327.477 | 2349.503 | 2354.110 | 2393.023 | 2363.952 | 2360.901 | 2336.269 | 2331.220 | 2314.654 | 2317.821 | 2337.118 | 2352.811 | 2362.330 | 2367.660 | 2376.613 | 2380.886 | 2402.277 | 2393.917 | 2397.149 | 2374.795 | 2397.457 | 2381.838 | 2398.852 | 2381.123 | 2440.723 | 2471.034 | 2495.005 | 2476.095 | 2464.924 | 2488.450 | 2498.628 | 2509.859 | 2515.646 | 2501.732 | 2475.083 | 2475.563 | 2469.365 | 2475.826 | 2427.843 | 2401.526 | 2368.533 | 2337.224 | 2305.878 | 2292.884 | 2277.712 | 2282.339 | 2278.929 | 2322.021 | 2368.377 | 2420.586 | 2449.848 | 2482.230 | 2518.714 | 2556.784 | 2580.724 | 2592.727 | 2591.473 | 2607.010 | 2657.466 | 2727.357 | 2830.789 | 2893.427 | 2951.086 | 2957.775 | 2966.494 | 2937.695 | 2898.732 | 2851.205 | 2847.664 | 2865.429 | 2908.589 | 2950.697 | 2986.174 | 3004.259 | 3021.107 | 3039.225 | 3042.726 | 3022.294 | 2985.509 | 2976.598 | 2971.280 | 3022.816 | 3032.851 | 3102.032 | 3132.088 | 3203.117 | 3199.751 |
| 11208 | 62019 | 9 | 11208 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | Kings County | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 2432.634 | 2468.666 | 2553.099 | 2571.974 | 2541.777 | 2549.192 | 2533.571 | 2596.307 | 2624.750 | 2660.759 | 2683.873 | 2685.560 | 2657.591 | 2672.800 | 2699.051 | 2825.592 | 2817.253 | 2797.145 | 2773.578 | 2815.385 | 2934.593 | 2977.254 | 3015.684 | 2987.130 | 2963.105 | 2895.445 | 2817.406 | 2858.719 | 2816.037 | 2895.667 |
| 11236 | 62046 | 16 | 11236 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | Kings County | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 2328.869 | 2376.032 | 2347.321 | 2400.155 | 2397.660 | 2524.344 | 2502.490 | 2582.495 | 2432.282 | 2429.336 | 2391.820 | 2451.315 | 2501.957 | 2598.722 | 2642.102 | 2672.396 | 2715.256 | 2700.885 | 2743.458 | 2753.950 | 2848.811 | 2899.215 | 2977.176 | 2935.365 | 2959.498 | 2847.246 | 2862.954 | 2976.389 |
| 10467 | 61807 | 17 | 10467 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | Bronx County | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 1349.679 | 1327.656 | 1351.738 | 1313.098 | 1331.150 | 1317.193 | 1307.569 | 1294.087 | 1354.713 | 1381.230 | 1443.584 | 1427.754 | NA | 1419.295 | 1427.326 | 1391.902 | 1388.167 | 1402.915 | 1443.141 | 1448.317 | 1415.071 | 1447.512 | 1475.749 | 1550.592 | 1557.876 | 1554.092 | 1551.874 | 1552.840 | 1580.368 | 1576.065 | 1554.715 | 1593.641 | 1588.411 | 1600.744 | 1578.046 | 1572.738 | 1587.081 | 1568.751 | 1613.196 | 1620.662 | 1685.971 | 1699.779 | 1695.050 | 1669.128 | 1649.561 | 1665.102 | 1668.471 | 1653.317 | 1612.794 | 1598.750 | 1655.226 | 1699.814 | 1745.707 | 1724.810 | 1774.450 | 1725.417 | 1744.514 | 1701.264 | 1737.235 | 1690.341 | 1715.512 | 1725.934 | 1751.695 | 1742.938 | 1772.303 | 1807.374 | 1812.226 | 1747.475 | 1728.976 | 1785.026 | 1831.988 | 1886.640 | 1881.483 | 1904.170 | 1937.096 | 1944.353 | 1931.878 | 1893.956 | 1891.447 | 1899.311 | 1929.648 | 1945.849 | 1958.650 | 1909.791 | 1963.970 | 2049.137 | 2084.984 | 2100.269 | 2182.744 | 2238.053 | 2317.342 | 2243.914 | 2269.451 | 2233.032 | 2244.841 | 2303.026 | 2282.180 | 2309.057 | 2294.031 | 2271.611 |
| 11373 | 62085 | 18 | 11373 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | Queens County | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 1872.391 | 1875.980 | 1908.656 | 1930.109 | 1949.615 | 1966.494 | 1910.506 | 1934.053 | 1923.586 | 1927.948 | 1969.994 | 2023.199 | 2100.825 | 2107.368 | 2138.288 | 2166.511 | 2151.894 | 2144.004 | 2141.909 | 2163.435 | 2181.641 | 2213.842 | 2226.211 | 2214.526 | 2217.911 | 2218.745 | 2253.525 | 2261.120 | 2295.725 | 2275.544 | 2302.135 | 2293.275 | 2290.069 | 2283.986 | 2273.511 | 2281.456 | 2302.458 | 2377.143 | 2439.551 | 2491.626 | 2476.333 |
| 11226 | 62037 | 19 | 11226 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | Kings County | 1919.726 | 1947.088 | 2038.567 | 2041.355 | 2053.751 | 2033.709 | 2056.747 | 2071.559 | 2092.795 | 2093.826 | 2095.349 | 2088.164 | 2089.653 | 2082.460 | 2131.828 | 2151.524 | 2171.467 | 2195.605 | 2235.378 | 2240.782 | 2202.912 | 2175.157 | 2203.503 | 2220.357 | 2230.477 | 2222.774 | 2227.372 | 2217.893 | 2224.578 | 2246.103 | 2268.897 | 2266.585 | 2253.781 | 2233.249 | 2214.707 | 2203.283 | 2212.000 | 2242.629 | 2265.593 | 2292.588 | 2295.173 | 2304.912 | 2320.557 | 2349.465 | 2369.397 | 2351.768 | 2334.290 | 2306.881 | 2322.166 | 2310.874 | 2337.374 | 2320.309 | 2348.144 | 2347.740 | 2377.157 | 2401.689 | 2419.742 | 2413.602 | 2378.537 | 2348.024 | 2357.056 | 2354.012 | 2390.353 | 2384.131 | 2394.843 | 2372.863 | 2375.547 | 2352.791 | 2321.016 | 2286.740 | 2268.131 | 2223.454 | 2180.768 | 2182.021 | 2209.309 | 2254.320 | 2278.554 | 2310.224 | 2349.893 | 2367.497 | 2398.880 | 2397.910 | 2409.960 | 2411.932 | 2437.651 | 2473.804 | 2515.255 | 2547.030 | 2591.051 | 2641.736 | 2678.524 | 2685.970 | 2685.640 | 2692.865 | 2686.209 | 2657.303 | 2651.083 | 2646.200 | 2676.835 | 2681.088 | 2706.442 | 2728.637 | 2748.451 | 2757.608 | 2743.802 | 2722.471 | 2713.343 | 2716.614 | 2745.009 | 2741.113 | 2737.821 | 2726.694 | 2750.361 | 2766.365 | 2815.689 | 2823.146 |
| 11207 | 62018 | 20 | 11207 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | Kings County | 1943.311 | 1851.295 | 1851.512 | 1876.733 | 1972.097 | 2025.955 | 2034.935 | 2016.905 | 2046.119 | 2052.770 | 2108.550 | 2062.484 | 2068.113 | 2075.443 | 2166.531 | 2198.191 | 2163.246 | 2134.050 | 2125.281 | 2149.885 | 2132.201 | 2131.459 | 2144.048 | 2150.612 | 2149.877 | 2119.797 | 2114.796 | 2124.847 | 2113.990 | 2110.918 | 2113.950 | 2154.685 | 2190.012 | 2209.270 | 2197.699 | 2195.972 | 2173.922 | 2161.329 | 2164.720 | 2225.315 | 2250.959 | 2259.032 | 2230.589 | 2259.636 | 2260.747 | 2241.267 | 2241.702 | 2241.726 | 2267.492 | 2262.747 | 2300.330 | 2282.050 | 2312.998 | 2308.482 | 2344.878 | 2341.534 | 2348.960 | 2356.870 | 2385.016 | 2409.248 | 2418.346 | 2406.290 | 2384.940 | 2397.553 | 2400.946 | 2390.648 | 2357.104 | 2326.858 | 2270.901 | 2224.135 | 2167.380 | 2164.536 | 2142.852 | 2121.733 | 2102.816 | 2111.997 | 2191.891 | 2261.879 | 2316.856 | 2336.262 | 2364.123 | 2412.807 | 2413.523 | 2448.975 | 2452.692 | 2473.511 | 2452.107 | 2492.918 | 2587.386 | 2702.735 | 2779.344 | 2818.346 | 2876.840 | 2890.292 | 2876.804 | 2835.782 | 2777.611 | 2765.606 | 2728.724 | 2759.512 | 2784.676 | 2860.680 | 2918.350 | 2963.556 | 3048.163 | 3032.274 | 2983.512 | 2865.312 | 2862.372 | 2874.016 | 2884.453 | 2935.159 | 3007.060 | 3054.124 | 3058.102 | 3047.897 |
| 10025 | 61639 | 29 | 10025 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | New York County | 3054.576 | 3053.302 | 3049.818 | 3073.585 | 3093.156 | 3120.443 | 3130.740 | 3128.406 | 3125.705 | 3126.853 | 3129.706 | 3125.624 | 3115.547 | 3111.635 | 3126.976 | 3134.421 | 3151.281 | 3162.171 | 3197.297 | 3212.951 | 3216.681 | 3176.803 | 3132.033 | 3082.978 | 3084.955 | 3095.278 | 3099.823 | 3112.193 | 3146.901 | 3192.288 | 3214.836 | 3206.462 | 3202.891 | 3160.709 | 3132.176 | 3091.163 | 3071.363 | 3080.146 | 3096.351 | 3142.287 | 3171.699 | 3201.336 | 3225.356 | 3229.365 | 3230.019 | 3222.493 | 3218.005 | 3240.672 | 3214.774 | 3209.740 | 3179.883 | 3224.126 | 3257.240 | 3300.126 | 3325.296 | 3347.873 | 3353.664 | 3335.318 | 3306.880 | 3298.485 | 3285.527 | 3304.568 | 3312.979 | 3291.845 | 3247.019 | 3170.925 | 3131.981 | 3039.923 | 2941.561 | 2862.996 | 2820.146 | 2794.729 | 2794.104 | 2800.058 | 2854.124 | 2893.835 | 2990.015 | 3081.440 | 3181.181 | 3263.018 | 3315.692 | 3343.263 | 3368.675 | 3410.190 | 3454.019 | 3509.981 | 3534.037 | 3583.593 | 3630.393 | 3719.811 | 3793.017 | 3843.228 | 3864.340 | 3817.788 | 3757.583 | 3704.425 | 3712.929 | 3707.666 | 3723.201 | 3759.911 | 3838.234 | 3912.598 | 3961.253 | 3980.527 | 3978.163 | 3907.273 | 3817.531 | 3708.716 | 3704.165 | 3744.395 | 3810.249 | 3885.781 | 3972.715 | 4065.404 | 4105.425 | 4120.227 |
| 11214 | 62025 | 32 | 11214 | zip | NY | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | Kings County | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | 1812.200 | 1747.007 | 1714.502 | 1654.343 | 1693.632 | 1729.120 | 1775.973 | 1784.677 | 1782.974 | 1776.790 | 1797.926 | 1771.361 | 1739.389 | 1725.426 | 1734.028 | 1769.674 | 1785.984 | 1810.862 | 1810.515 | 1799.015 | 1803.156 | 1867.801 | 1884.229 | 1919.981 | 1907.645 | 1965.035 | 1955.297 | 1937.294 | 1928.016 | 1967.854 | 1990.338 | 1985.219 | 1982.035 | 1988.510 | 1991.942 | 2034.035 | 2044.267 | 2086.091 | 2123.956 | 2135.086 | 2153.204 | 2095.801 | 2123.148 | 2110.223 | 2162.314 | 2154.495 | 2174.464 | 2197.800 | 2244.626 | 2308.543 | 2326.571 | 2251.930 | 2211.409 | 2232.405 |

Step 3B: need to make ZORI long format

``` r
zori_long=
  zori_clean %>% 
  pivot_longer(
    cols=x2015_01_31:x2024_08_31,
    names_to="date",
    values_to="rent") %>% 
 mutate(
   date=str_remove(date,"x")) %>% 
     select(zip,date,rent) %>% 
     arrange(zip,date)
knitr::kable(head(zori_long,10))
```

| zip   | date       |     rent |
|:------|:-----------|---------:|
| 10001 | 2015_01_31 | 3855.089 |
| 10001 | 2015_02_28 | 3892.376 |
| 10001 | 2015_03_31 | 3898.212 |
| 10001 | 2015_04_30 | 3969.644 |
| 10001 | 2015_05_31 | 4033.221 |
| 10001 | 2015_06_30 | 4070.808 |
| 10001 | 2015_07_31 | 4067.258 |
| 10001 | 2015_08_31 | 4069.862 |
| 10001 | 2015_09_30 | 4039.812 |
| 10001 | 2015_10_31 | 4023.490 |

Step 3C Part1: merging zip info due to warning error many

``` r
zip_one_per_zip =
  zip_clean |>
  group_by(zip) |>
  slice(1) |>     
  ungroup()
```

Some ZIP codes span multiple neighborhoods; to avoid row inflation later
on, I keep one neighborhood per ZIP (first alphabetically). This
preserves correct ZIP-level counts while keeping the dataset tidy.

Step 3C Part2: merge data sets

``` r
final_df=
  left_join(zori_long,zip_one_per_zip,by="zip") %>% 
  relocate(zip,borough,neighborhood,date,rent) %>% 
  arrange(zip,date)
knitr::kable(head(final_df,10))
```

| zip   | borough  | neighborhood        | date       |     rent |
|:------|:---------|:--------------------|:-----------|---------:|
| 10001 | New York | Chelsea and Clinton | 2015_01_31 | 3855.089 |
| 10001 | New York | Chelsea and Clinton | 2015_02_28 | 3892.376 |
| 10001 | New York | Chelsea and Clinton | 2015_03_31 | 3898.212 |
| 10001 | New York | Chelsea and Clinton | 2015_04_30 | 3969.644 |
| 10001 | New York | Chelsea and Clinton | 2015_05_31 | 4033.221 |
| 10001 | New York | Chelsea and Clinton | 2015_06_30 | 4070.808 |
| 10001 | New York | Chelsea and Clinton | 2015_07_31 | 4067.258 |
| 10001 | New York | Chelsea and Clinton | 2015_08_31 | 4069.862 |
| 10001 | New York | Chelsea and Clinton | 2015_09_30 | 4039.812 |
| 10001 | New York | Chelsea and Clinton | 2015_10_31 | 4023.490 |

``` r
total_observations = nrow(final_df)        # total rows
unique_zips_final = length(unique(final_df$zip)) # 149
unique_neighborhoods = length(unique(na.omit(zip_clean$neighborhood)))
```

The final data set has **17284 observations, 149 unique zips and 42
unique neighbhorhoods.**

Step 4: now looking for zips that don’t show up in ZORI

``` r
zips_in_zori = tibble(zip = unique(zori_clean$zip))
zips_in_zip  = tibble(zip = unique(zip_clean$zip))

zips_not_in_zori_tbl =
  zip_clean |>
  anti_join(zips_in_zori, by = "zip") |>
  arrange(borough, zip)

zips_not_in_zori_amount=nrow(zips_not_in_zori_tbl)
zips_not_in_zori_amount
```

    ## [1] 171

``` r
knitr::kable(head(zips_not_in_zori_tbl, 15))
```

| zip   | borough | neighborhood               |
|:------|:--------|:---------------------------|
| 10464 | Bronx   | Southeast Bronx            |
| 10474 | Bronx   | Hunts Point and Mott Haven |
| 10475 | Bronx   | Northeast Bronx            |
| 10499 | Bronx   | NA                         |
| 10550 | Bronx   | NA                         |
| 10704 | Bronx   | NA                         |
| 10705 | Bronx   | NA                         |
| 10803 | Bronx   | NA                         |
| 11202 | Kings   | NA                         |
| 11224 | Kings   | Southern Brooklyn          |
| 11239 | Kings   | Canarsie and Flatlands     |
| 11241 | Kings   | NA                         |
| 11242 | Kings   | NA                         |
| 11243 | Kings   | NA                         |
| 11245 | Kings   | NA                         |

I found that there were **171** ZIP codes that appear in the NYC ZIP
file but are missing from Zori. For example, ZIP 10464 (Southeast
Bronx), ZIP 10474 (Hunts Point and Mott Haven), and ZIP 11224 (Southern
Brooklyn) are listed in the city ZIP file but not included in Zillow.
This likely reflects areas with limited rental housing,
industrial/commercial zones, or ZIP codes that are primarily PO
Box–only. Zillow excludes these areas because there would not be enough
info to calculate the Zori index.

Step 5: Compare rental prices in January 2021 to prices in January 2020.
Make a table that shows the 10 ZIP codes (along with the borough and
neighborhood) with largest drop in price from January 2020 to 2021.

``` r
jan_drop_tbl =
  final_df |>
  filter(date %in% c("2020_01_31", "2021_01_31")) |>
  group_by(zip, borough, neighborhood) |>
  summarise(
    jan2020 = rent[date == "2020_01_31"],
    jan2021 = rent[date == "2021_01_31"],
    .groups = "drop"
  ) |>
  mutate(drop_2020_to_2021 = jan2021 - jan2020) |>
  filter(!is.na(drop_2020_to_2021)) |>
  arrange(drop_2020_to_2021)
knitr::kable(head(jan_drop_tbl, 10))
```

| zip | borough | neighborhood | jan2020 | jan2021 | drop_2020_to_2021 |
|:---|:---|:---|---:|---:|---:|
| 10007 | New York | Lower Manhattan | 6334.211 | 5421.614 | -912.5966 |
| 10069 | New York | NA | 4623.042 | 3874.918 | -748.1245 |
| 10009 | New York | Lower East Side | 3406.442 | 2692.187 | -714.2550 |
| 10016 | New York | Gramercy Park and Murray Hill | 3731.135 | 3019.431 | -711.7045 |
| 10001 | New York | Chelsea and Clinton | 4108.098 | 3397.648 | -710.4499 |
| 10002 | New York | Lower East Side | 3645.416 | 2935.113 | -710.3028 |
| 10004 | New York | Lower Manhattan | 3149.658 | 2443.697 | -705.9608 |
| 10038 | New York | Lower Manhattan | 3573.201 | 2875.616 | -697.5853 |
| 10012 | New York | Greenwich Village and Soho | 3628.566 | 2942.344 | -686.2218 |
| 10010 | New York | Gramercy Park and Murray Hill | 3697.284 | 3012.353 | -684.9304 |
