---
title: "p8105_hw2_jkh2157"
output: github_document
date: "2025-09-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Libraries 

```{r}
library(tidyverse)
library(knitr)
```

## Problem 1

Step 1a: Clean the data in pols-month

```{r}
pols_df=
  read_csv("datasets/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate (mon, into = c("year","month","day"),sep="-") %>% 
  mutate(
    month = recode(month,`01`="Jan",`02`="Feb",`03`="Mar",`04`="Apr",`05`="May",`06`="Jun",`07`="Jul",`08`="Aug",`09`="Sep",`10`="Oct",`11`="Nov",`12`="Dec"),
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem ==1 ~ "dem"
    ),
    year=as.character(year)
  ) %>% 
  select(year,month,president,everything(),-day,-prez_gop,-prez_dem)
knitr::kable(head(pols_df,10))
```

Step 1b: Clean the data for snp.csv 

```{r}
snp_df=
  read_csv("datasets/fivethirtyeight_datasets/snp.csv") %>% 
  separate(date, into=c("month","date","year"), sep = "/") %>% 
  mutate(
    month = recode(month,`1`="Jan",`2`="Feb",`3`="Mar",`4`="Apr",`5`="May",`6`="Jun",`7`="Jul",`8`="Aug",`9`="Sep",`10`="Oct",`11`="Nov",`12`="Dec"),
    year=case_when(
      as.numeric(year)>=50 ~ paste0("19",year),
      as.numeric(year)<50 ~ paste0("20",year)
    )) %>% 
  mutate(year=as.character(year)) %>% 
  select(year,month,close) %>% 
  arrange(year,month)
knitr::kable(head(snp_df,10))
```

